# Created with YamlCreate.ps1 v2.4.6 $debug=NVS0.CRLF.5-1-26100-4484.Win32NT
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.10.0.schema.json

PackageIdentifier: Der_Floh.VideoToAscii
PackageVersion: 1.1.2
PackageLocale: en-US
Publisher: Der_Floh
PublisherUrl: https://github.com/Der-Floh
# PublisherSupportUrl:
# PrivacyUrl:
Author: Der_Floh
PackageName: VideoToAscii
PackageUrl: https://github.com/Der-Floh/Video-To-Ascii
License: MIT
LicenseUrl: https://github.com/Der-Floh/Video-To-Ascii/blob/main/LICENSE.txt
# Copyright:
# CopyrightUrl:
ShortDescription: A .NET console tool that converts and plays videos as ASCII art in the terminal.
Description: VideoToAscii converts and streams any video file or webcam input as colourful ASCII characters directly in your terminal. Supports multiple conversion strategies, optional audio playback and output files.
Moniker: videotoascii
Tags:
- ascii
- ascii-art
- console-app
- converter
- dotnet
- media-player
- terminal
- video
- video-processing
# ReleaseNotes:
# ReleaseNotesUrl:
# PurchaseUrl:
# InstallationNotes:
# Documentations:
ManifestType: defaultLocale
ManifestVersion: 1.10.0
