# Created with YamlCreate.ps1 v2.4.6 $debug=NVS0.CRLF.5-1-26100-4484.Win32NT
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: der_floh.videotoascii
PackageVersion: 1.1.8
InstallerLocale: en-US
InstallerType: zip
Commands:
- videotoascii
ReleaseDate: 2025-07-02
ArchiveBinariesDependOnPath: true
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.DotNet.Runtime.8
    MinimumVersion: 8.0.0
  - PackageIdentifier: Gyan.FFmpeg
    MinimumVersion: 5.0
Installers:
- Architecture: neutral
  NestedInstallerType: portable
  NestedInstallerFiles:
  - RelativeFilePath: VideoToAscii.exe
    PortableCommandAlias: videotoascii
  InstallerUrl: https://github.com/Der-Floh/Video-To-Ascii/releases/download/v1.1.8/VideoToAscii-v1.1.8.zip
  InstallerSha256: 183EDA31E14C2D33A59C55A9C2FCEC60D31F886A67F336926C4D4367CE126BA2
ManifestType: installer
ManifestVersion: 1.10.0
